arch:
  - amd64
  - arm64
services:
  - docker
script: docker run --name=openresty --rm wise2c/python-openresty openresty -v

#assuming docker image wise2c/python-openresty is amd64 and arm64v8 ready
